variable "name" {}
variable "resource_group_name" {}
variable "location" {}
variable "sql_version" {}
variable "administrator_login" {}
variable "administrator_login_password" {}
variable "connection_policy" {}
variable "minimum_tls_version" {}
variable "public_network_access_enabled" {}
variable "login_username" {}
variable "object_id" {}
variable "tenant_id" {}
variable "azuread_authentication_only" {}
variable "type" {}
variable "identity_ids" {}